# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

env:
  matrix:
    - TOXENV=check
    - TOXENV=docs

matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27,report,codecov
    - python: 3.5
      env:
        - TOXENV=py35,report,codecov
    - python: 3.6
      env:
        - TOXENV=py36,report,codecov

before_install:

# Get local information about the machine
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip setuptools

# Install various required modules
  - pip install tox

script:
  - tox -v

# after_success:
#   - ./tools/travis-upload-wheel.sh

notifications:
    email: false

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

after_success:
  - codecov
